#!/usr/bin/env python3
"""Generate references/COVERAGE.md: which corpus pages the rule sheets actually cite.

Mechanical, so the skill can never quietly overclaim its own coverage again.
Exit 1 if the summary in README.md disagrees with reality.
"""
import pathlib, re, sys, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
pages = sorted(p.relative_to(ROOT).as_posix() for p in DOCS.rglob("*.md"))

cited = set()
prose = []
SELF = "COVERAGE.md"  # this report LISTS uncovered paths; counting it would prove them covered
for f in list((ROOT / "references").glob("*.md")) + [ROOT / "SKILL.md", ROOT / "README.md", ROOT / "audit.mjs"]:
    if not f.exists() or f.name == SELF:
        continue
    prose.append(f.read_text(errors="replace"))
blob = "\n".join(prose)
for p in pages:
    # A page counts as cited only when something PATH-SHAPED points at it: the full repo path, or
    # the path with the docs/ prefix stripped (e.g. "crawling-indexing/sitemaps/build-sitemap").
    # Matching a bare stem would score `video.md` as covered because some sheet says "video" --
    # which is how the first version of this script reported a fraudulent 158/158.
    rel = p.replace("docs/search/docs/", "").replace("docs/crawling/docs/", "")[:-3]
    # `docs/search/docs.md` -> rel `docs/search/docs`, a substring of literally every other path.
    # Guard: a rel that is a prefix of the corpus root proves nothing.
    if "/" not in rel or rel.startswith("docs/"):
        if p in blob:
            cited.add(p)
        continue
    if p in blob or rel in blob:
        cited.add(p)

missing = [p for p in pages if p not in cited]
by_sec = collections.defaultdict(list)
for p in missing:
    rel = p.replace("docs/search/docs/", "").replace("docs/crawling/docs/", "crawling/")
    by_sec[rel.split("/")[0] if "/" in rel else "root"].append(p)

# Pages we deliberately don't summarize, with the reason. Kept explicit so "not summarized" never
# gets read as "overlooked".
DELIBERATE = {
    "docs/search/docs/guides/javascript-seo-basics.md": "byte-duplicate of crawling-indexing/javascript/javascript-seo-basics.md",
    "docs/search/docs/appearance/visual-elements-gallery.md": "glossary of SERP visual elements; nothing to enforce",
    "docs/search/docs/monitor-debug/search-operators/image-search.md": "Google Images operators; debugging aid, no site requirement",
    "docs/search/docs/fundamentals/get-on-google.md": "navigational hub",
    "docs/search/docs/fundamentals/get-started.md": "navigational hub",
    "docs/search/docs/fundamentals/get-started-developers.md": "navigational hub",
    "docs/search/docs/appearance.md": "section hub",
    "docs/search/docs/crawling-indexing.md": "section hub",
    "docs/search/docs.md": "site hub",
    "docs/search/docs/specialty/ecommerce.md": "section hub",
    "docs/search/docs/specialty/international.md": "section hub",
    "docs/search/docs/monitor-debug/security.md": "section hub",
}

out = ["# Coverage: corpus vs. rule sheets", "",
       f"`docs/` holds **{len(pages)} of 158** Google Search Central pages — the corpus is complete.",
       f"The `references/` sheets summarize **{len(cited)}** of them ({len(cited)*100//len(pages)}%).", "",
       "The sheets are a working subset for auditing a typical site. They are **not** a replacement",
       "for the corpus. For anything below, or anything you're unsure of, **grep `docs/` directly.**",
       "",
       "This file is generated by `scripts/coverage.py` from path-shaped citations, so the number",
       "above cannot drift away from reality.", ""]
unexplained = [p for p in missing if p not in DELIBERATE]
explained = [p for p in missing if p in DELIBERATE]

if explained:
    out += ["## Not summarized on purpose", "",
            "| page | why |", "|---|---|"]
    out += [f"| `{p}` | {DELIBERATE[p]} |" for p in sorted(explained)]
    out.append("")
if unexplained:
    out += [f"## Not yet summarized ({len(unexplained)}) — gaps, not decisions", ""]
    for sec in sorted(by_sec):
        rows = [p for p in sorted(by_sec[sec]) if p in unexplained]
        if not rows:
            continue
        out.append(f"**{sec}**")
        out += [f"- `{p}`" for p in rows]
        out.append("")
else:
    out += ["Every remaining page is either summarized or listed above as a deliberate omission.", ""]

(ROOT / "references" / "COVERAGE.md").write_text("\n".join(out) + "\n")
print(f"corpus={len(pages)} cited={len(cited)} missing={len(missing)}")
